# Generated by Django 2.1.7 on 2019-03-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_remove_actor_movies'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='actors.Actor'),
        ),
    ]
